// Generated by CoffeeScript 1.3.3
(function() {
  var JadeHandlebarsCompiler, handlebars, jade, sysPath;

  jade = require('jade');

  handlebars = require('handlebars');

  sysPath = require('path');

  module.exports = JadeHandlebarsCompiler = (function() {

    JadeHandlebarsCompiler.prototype.brunchPlugin = true;

    JadeHandlebarsCompiler.prototype.type = 'template';

    JadeHandlebarsCompiler.prototype.extension = 'jhbs';

    JadeHandlebarsCompiler.prototype.pattern = /\.(?:jhbs|jhandlebars)$/;

    function JadeHandlebarsCompiler(config) {
      this.config = config;
      null;
    }

    JadeHandlebarsCompiler.prototype.compile = function(data, path, callback) {
      var content, error, jadeOutput, result;
      try {
        jadeOutput = jade.compile(data, {
          compileDebug: false,
          filename: path
        });
        content = handlebars.precompile(jadeOutput());
        return result = "module.exports = Handlebars.template(" + content + ");";
      } catch (err) {
        return error = err;
      } finally {
        callback(error, result);
      }
    };

    JadeHandlebarsCompiler.prototype.include = [sysPath.join(__dirname, '..', 'node_modules', "handlebars", "lib", 'handlebars.runtime.js')];

    return JadeHandlebarsCompiler;

  })();

}).call(this);
